### ISSUE TITLE
Annotation for form-configuration

### ISSUE THREAD

**Issue by SBolsec** [croz-ltd/nrich#124]
## Basic information

* nrich version: 1.4.1
* Module: nrich-form-configuration

## Enhancement description

Add a class annotation for defining form id.
The proposed name for the annotation is `@FormConfiguration`.
Both ways would be supported, defining mappings through property files and using the annotation.
If both are used, the property file would take precedence.

### Current behaviour

Mappings between form id and corrresponding clases have to be defined in a property file.

```yml
nrich.form-configuration:
  default-converter-enabled: true
  form-configuration-mapping:
    user.create-form: net.croz.nrich.example.CreateUserRequest
    user.update-form: net.croz.nrich.example.UpdateUserRequest
```

### Wanted behaviour

Use annotation to define form id.

```java
@FormConfiguration("user.create-form")
public class CreateUserRequest {
   ...
}
```
